services:
  # --- PostgreSQL ---
  postgres:
    image: postgres:16-alpine
    container_name: docarreto-postgres
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: senha_secreta
      POSTGRES_DB: app_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- Redis ---

# Criação de Volumes para persistência
volumes:
  postgres_data:
