"""removendo username, criando email como unique

Revision ID: 6faf0ee2d5a5
Revises: 71054350a9b1
Create Date: 2026-03-13 19:57:04.319835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6faf0ee2d5a5'
down_revision: Union[str, Sequence[str], None] = '71054350a9b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
