"""tabela de criador de demandas e candidaturas

Revision ID: 9ca6c703b63b
Revises: 6faf0ee2d5a5
Create Date: 2026-03-19 21:34:25.520976

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ca6c703b63b"
down_revision: str | Sequence[str] | None = "6faf0ee2d5a5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "criadordemanda",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("avaliacao_media", sa.Float(), nullable=False),
        sa.Column("total_demandas", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "demand",
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "endereco_origem", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("lat_origem", sa.Float(), nullable=False),
        sa.Column("lon_origem", sa.Float(), nullable=False),
        sa.Column(
            "endereco_destino", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("lat_destino", sa.Float(), nullable=False),
        sa.Column("lon_destino", sa.Float(), nullable=False),
        sa.Column("valor_proposto", sa.Float(), nullable=False),
        sa.Column("peso_carga_kg", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ABERTA", "EM_ANDAMENTO", "CONCLUIDA", "CANCELADA", name="demandstatus"
            ),
            nullable=False,
        ),
        sa.Column("data_coleta", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "candidatura",
        sa.Column("demanda_id", sa.Uuid(), nullable=False),
        sa.Column("entregador_id", sa.Uuid(), nullable=False),
        sa.Column("mensagem", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDENTE", "ACEITA", "RECUSADA", name="candidaturastatus"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["demanda_id"], ["demand.id"]),
        sa.ForeignKeyConstraint(["entregador_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    usertypes_enum = sa.Enum("CRIADOR_DEMANDA", "ENTREGADOR", name="usertypes")
    usertypes_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "user",
        sa.Column(
            "tipo_user",
            usertypes_enum,
            nullable=False,
            server_default="CRIADOR_DEMANDA",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "tipo_user")
    op.drop_table("candidatura")
    op.drop_table("demand")
    op.drop_table("criadordemanda")
    sa.Enum(name="usertypes").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
