"""tabela de entregador

Revision ID: e987abc75d61
Revises: 9ca6c703b63b
Create Date: 2026-03-19 21:40:42.729718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e987abc75d61'
down_revision: Union[str, Sequence[str], None] = '9ca6c703b63b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entregador',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cnh', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_veiculo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('placa_veiculo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('capacidade_kg', sa.Float(), nullable=False),
    sa.Column('avaliacao_media', sa.Float(), nullable=False),
    sa.Column('total_entregas', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entregador')
    # ### end Alembic commands ###
